name: Build/release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify the Python version you need

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydicom numpy pillow
          pip install -U pyinstaller

      - name: Run PyInstaller
        run: |
          cd scripts # Change to the directory containing your Python script
          pyinstaller preprocessing.py -F --collect-submodules=pydicom

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Specify the Node.js version you need
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
      - run: npm run build

      - name: Check
      - run: cd dist && ls
