name: Build/release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Set tag name without 'v'
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify the Python version you need

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydicom numpy pillow
          pip install -U pyinstaller

      - name: Run PyInstaller
        run: |
          cd scripts # Change to the directory containing your Python script
          pyinstaller preprocessing.py -F --collect-submodules=pydicom

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive Windows artifacts
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path dist/win-unpacked/* -DestinationPath "Label-${{ env.TAG_NAME }}-windows.zip"
          mv "dist/Label Setup ${{ env.TAG_NAME }}.exe" .
        shell: pwsh

      # - name: Archive Linux artifacts
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     tar -czvf "Label-${{ env.TAG_NAME }}.tar.gz" -C dist/linux-unpacked .
      #     mv dist/Label-${{ env.TAG_NAME }}.AppImage .

      - name: Prepare MacOS artifacts
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/Label-${{ env.TAG_NAME }}-arm64-mac.zip .
          mv dist/Label-${{ env.TAG_NAME }}-arm64.dmg .
          
      - name: Upload Windows artifacts to release
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: |
            Label-${{ env.TAG_NAME }}-windows.zip
            Label Setup ${{ env.TAG_NAME }}.exe

      - name: Upload MacOS artifacts to release
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: |
            Label-${{ env.TAG_NAME }}-arm64-mac.zip
            Label-${{ env.TAG_NAME }}-arm64.dmg
